### ISSUE TITLE
Migrate docker image to Decidim organization  

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim-bulletin-board#210]
At the moment the docker image is published at https://hub.docker.com/r/codegram/decidim-bulletin-board

It should be available in decidim own docker organization, ie https://hub.docker.com/r/decidim/decidim-bulletin-board

The same with the rest of the images used in this project and its references: 

https://github.com/decidim/decidim-bulletin-board/blob/d4ef3757b77b5abc7bc6d3c8b57a6408302480ef/.github/workflows/server-workflow.yml
https://github.com/decidim/decidim-bulletin-board/blob/93ce71926100c3081bd592b0cd97f2221d4725e6/Dockerfile.web
https://github.com/decidim/decidim-bulletin-board/blob/93ce71926100c3081bd592b0cd97f2221d4725e6/Dockerfile.worker
https://github.com/decidim/decidim-bulletin-board/blob/6456923efdc423cd5ba4a9514c39a79f033d3cf1/.devcontainer/Dockerfile
https://github.com/decidim/decidim-bulletin-board/blob/6456923efdc423cd5ba4a9514c39a79f033d3cf1/.github/workflows/voting-scheme-electionguard-python-wrapper-workflow.yml
https://github.com/decidim/decidim-bulletin-board/blob/93ce71926100c3081bd592b0cd97f2221d4725e6/voting_schemes/electionguard/makefile.mk
https://github.com/decidim/decidim-bulletin-board/blob/6456923efdc423cd5ba4a9514c39a79f033d3cf1/voting_schemes/electionguard/python-to-js/build
https://github.com/decidim/decidim-bulletin-board/blob/93ce71926100c3081bd592b0cd97f2221d4725e6/bulletin_board/server.mk

**Comment by ahukkanen** [comment]
We have published two of the images under Decidim organization after merging #251:
- The base image: [decidim/ruby-node-python-electionguard](https://hub.docker.com/r/decidim/ruby-node-python-electionguard)
- The bulletin board server image: [decidim/decidim-bulletin-board](https://hub.docker.com/r/decidim/decidim-bulletin-board)

The [pyodiode-electionguard](https://hub.docker.com/r/codegram/pyodide-electionguard) image is still under codegram as it was not necessary to update for #251. This can be migrated in future releases under the Decidim organization.

Since this one image is still not migrated, I'll leave this issue open for the time being.
